# Generated by Django 2.2.6 on 2019-11-05 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandLord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('identification_type', models.CharField(choices=[('National ID', 'National ID'), ('Passport', 'Passport'), ('Drivers License', 'Drivers License'), ('Company Tax Clearance', 'Company Tax Clearance')], max_length=55)),
                ('identification', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('bank_branch', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('representative', models.CharField(blank=True, max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='manager.Country')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nationality', to='manager.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Residential', 'Residential'), ('Apartment', 'Apartment'), ('Office', 'Office'), ('Industrial', 'Industrial'), ('Commercial', 'Commercial'), ('Agricultural', 'Agricultural'), ('Land', 'Land')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('property_value', models.DecimalField(blank=True, decimal_places=3, max_digits=15)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('lot_size', models.DecimalField(decimal_places=3, max_digits=15)),
                ('building_size', models.DecimalField(decimal_places=3, max_digits=15)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('details', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Country')),
                ('land_lord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.LandLord')),
                ('organisation_managing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255)),
                ('is_vacant', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_number_of_tenants', models.IntegerField(default=1)),
                ('rental_value', models.DecimalField(decimal_places=3, max_digits=15)),
                ('service_fees', models.DecimalField(decimal_places=3, max_digits=15)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_occupancy', models.DateField()),
                ('identification_type', models.CharField(choices=[('National ID', 'National ID'), ('Passport', 'Passport'), ('Drivers License', 'Drivers License'), ('Company Tax Clearance', 'Company Tax Clearance')], max_length=55)),
                ('identification', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_address', models.CharField(max_length=255)),
                ('tenant_representative', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Country')),
                ('property_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.PropertyUnit')),
            ],
        ),
    ]
