# Generated by Django 2.2.6 on 2019-11-05 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_landlord_property_propertyunit_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
