# Generated by Django 2.2.6 on 2019-11-05 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_landlord_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='created_by',
        ),
        migrations.AddField(
            model_name='landlord',
            name='managed_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='manager.Organisation'),
        ),
    ]
