# Generated by Django 2.2.6 on 2019-11-05 10:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20191105_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 11, 5, 10, 18, 2, 224799, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
