# Generated by Django 2.2.6 on 2019-11-07 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_landlord_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='acquisition_cost',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='first_erected_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='geographic_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='management_started_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='management_stopped_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='property_acquired_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='property_disposed_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='zone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
