# Generated by Django 2.2.6 on 2019-11-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20191107_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='date_added',
            new_name='date_created',
        ),
    ]
