# Generated by Django 2.2.6 on 2019-11-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20191107_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
