# Generated by Django 2.2.6 on 2019-11-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20191107_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
