# Generated by Django 2.2.6 on 2019-11-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20191107_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='identification_type',
            field=models.CharField(choices=[('National ID', 'National ID'), ('Passport', 'Passport'), ('Drivers License', 'Drivers License'), ('Company Tax Clearance', 'Company Tax Clearance'), ('Other', 'Other')], max_length=55),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Apartment', 'Apartment'), ('Office', 'Office'), ('Industrial', 'Industrial'), ('Commercial', 'Commercial'), ('Agricultural', 'Agricultural'), ('Land', 'Land'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_value',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='identification_type',
            field=models.CharField(choices=[('National ID', 'National ID'), ('Passport', 'Passport'), ('Drivers License', 'Drivers License'), ('Company Tax Clearance', 'Company Tax Clearance'), ('Other', 'Other')], max_length=55),
        ),
    ]
