# Generated by Django 2.2.6 on 2019-11-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20191107_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='acquisition_cost',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='building_size',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='lot_size',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=15),
        ),
    ]
