# Generated by Django 2.2.6 on 2019-11-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_auto_20191108_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='acquisition_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='building_size',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='lot_size',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Apartment Building', 'Apartment Building'), ('Office Building', 'Office Building'), ('Industrial', 'Industrial'), ('Commercial', 'Commercial'), ('Agricultural', 'Agricultural'), ('Land', 'Land'), ('Retail', 'Retail'), ('Other', 'Other')], max_length=55),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
