# Generated by Django 2.2.6 on 2019-11-16 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_auto_20191109_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premise_title', models.CharField(max_length=255)),
                ('accommodation_type', models.CharField(choices=[('Offices', 'Offices'), ('Parking', 'Parking'), ('Retail', 'Retail'), ('Houses', 'Houses')], max_length=55)),
                ('total_area', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('is_vacant', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='propertyunit',
            name='max_number_of_tenants',
        ),
        migrations.RemoveField(
            model_name='propertyunit',
            name='rental_value',
        ),
        migrations.RemoveField(
            model_name='propertyunit',
            name='service_fees',
        ),
        migrations.AddField(
            model_name='propertyunit',
            name='total_area',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Apartment Building', 'Apartment Building'), ('Industrial', 'Industrial'), ('Commercial', 'Commercial'), ('Agricultural', 'Agricultural'), ('Land', 'Land'), ('Retail', 'Retail'), ('Other', 'Other')], max_length=55),
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.AddField(
            model_name='premise',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Property'),
        ),
    ]
