# Generated by Django 2.2.6 on 2019-11-17 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_auto_20191116_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=255)),
                ('trading_as_list_name', models.CharField(max_length=255)),
                ('identification_type', models.CharField(choices=[('National ID', 'National ID'), ('Passport', 'Passport'), ('Drivers License', 'Drivers License'), ('Company Tax Clearance', 'Company Tax Clearance'), ('Other', 'Other')], max_length=55)),
                ('identification', models.CharField(max_length=255)),
                ('email_1', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_1', models.CharField(max_length=20)),
                ('phone_2', models.CharField(blank=True, max_length=20, null=True)),
                ('postal_address', models.TextField()),
                ('domicile_address', models.TextField()),
                ('details', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Country')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_representative', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant_representative_capacity', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_representative', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_representative_capacity', models.CharField(blank=True, max_length=255, null=True)),
                ('lease_starts', models.DateField()),
                ('occupation_date', models.DateField()),
                ('lease_ends', models.DateField(blank=True, null=True)),
                ('lease_indefinite_thereafter', models.BooleanField(default=False)),
                ('rent_review_date', models.DateField()),
                ('annual_rent_review_date', models.DateField()),
                ('rent_review_notes', models.TextField()),
                ('monthly_rent_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('escalation_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('recovery_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('monthly_recovery_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('recovery_notes', models.TextField()),
                ('cash_deposit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('bank_guarantee_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('deposit_notes', models.TextField()),
                ('lease_documentation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('late_payment_interest_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by_manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.PropertyManager')),
                ('organization_managing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Organisation')),
                ('owner_lessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.LandLord')),
                ('premises', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Premise')),
                ('property_unit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.PropertyUnit')),
                ('tenant_lessee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.Tenant')),
            ],
        ),
    ]
