# Generated by Django 2.2.6 on 2019-11-18 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_lease_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='lease',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lease', to='manager.Lease'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lease',
            name='tenant_lessee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='manager.Tenant'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='domicile_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
