# Generated by Django 2.2.6 on 2019-11-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_lease_entire_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='deposit_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='recovery_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='rent_review_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
